print("♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡")
print("Minha primeira automação")
print("♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡")
nome = input("Qual é o seu nome? ")
idade = input("Quantos anos você tem?")
print()
print("Olá,", nome, "💗")
print("Você tem", idade, "anos!")
print("Seja bem-vinda ao mundo da programação♡")
